[tool.poetry]
name = "nigeria-geodata"
version = "0.1.0"
description = ""
authors = ["jeafreezy <jolaiyaemmanuel@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pre-commit = "^3.7.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
